CREATE TABLE [dbo].[Transactions]
(
	[TransactionId] INT NOT NULL PRIMARY KEY,
	[OrderId] INT NOT NULL,
	[TotalAmount] DECIMAL(10, 2) NOT NULL,
	[PaymentMethod] NVARCHAR(50) NOT NULL,
	[SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL, 
    CONSTRAINT [FK_Transactions_Orders] FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])

)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[dbo].[Transactions_HISTORY], DATA_CONSISTENCY_CHECK=ON))
